#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nginx'
cookbook 'postgresql'
cookbook 'ffmpeg'
cookbook 'git'
cookbook 'couchdb'
cookbook 'nodejs'
cookbook 'redisio'
cookbook 'user'
cookbook 'sudo'
cookbook 'application'

cookbook "git_ssh_wrapper",
  :git => "https://github.com/OpenWatch/chef-git_ssh_wrapper.git"

cookbook "openssh",
  :git => "https://github.com/fnichol/chef-openssh.git",
  :ref => "v0.8.3"

cookbook "hostname",
  :git => "https://github.com/franco/chef-hostname.git"

# in site-cookbooks during development
#cookbook "application_python",
#  :git => "https://github.com/OpenWatch/application_python.git"

cookbook "database",
  :git => "https://github.com/opscode-cookbooks/database.git"
