#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nginx'
cookbook 'postgresql'
cookbook 'ffmpeg'
cookbook 'git'
cookbook 'couchdb'
cookbook 'nodejs'
cookbook 'redisio'
cookbook 'user'

cookbook "chef-ssh-wrapper",
  :git => "https://github.com/OpenWatch/chef-git_ssh_wrapper.git"