#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'nginx'
cookbook 'postgresql'
cookbook 'ffmpeg'
cookbook 'git'
cookbook 'couchdb'
cookbook 'nodejs'
cookbook 'redisio'
cookbook 'user'
cookbook 'sudo'
cookbook 'application'
cookbook 'application_python'
cookbook 'yasm'
cookbook 'ubuntu'
cookbook 'database'
cookbook 'rabbitmq'
cookbook 'firewall'

cookbook "git_ssh_wrapper",
  :git => "https://github.com/OpenWatch/chef-git_ssh_wrapper.git"

cookbook "openssh",
  :git => "https://github.com/fnichol/chef-openssh.git",
  :ref => "v0.8.3"

cookbook "vt-gpg",
  :git => "https://github.com/VendaTech/chef-cookbook-gpg.git"
